name: guardian
description: A new Flutter project.

publish_to: "none" 


version: 1.0.0+1

environment:
    sdk: ">=3.0.0-290.0.dev <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    
    logger: ^2.0.0-nullsafety 
    cupertino_icons: ^1.0.2
    introduction_screen: ^3.1.8
    cloud_firestore: ^4.7.1
    firebase_core: ^2.13.0
    firebase_auth: ^4.4.1
    google_sign_in: ^5.0.0-nullsafety
    video_player_control_panel: ^1.1.0
    dio: ^5.1.2
    flutterfire_cli: ^0.2.7
    flutter_native_splash: ^2.2.4
    http: ^0.13.4
    universal_html: ^2.2.2
    camera:
        git:
            url: https://github.com/flutter/plugins
            path: packages/camera/camera
    android_intent: ^2.0.2
    permission_handler: ^11.0.0
    flutter_local_notifications: ^15.1.1
    socket_io_client: ^2.0.3
    provider: ^6.0.5
    flutter_webrtc: ^0.9.45
    quiver: ^3.2.1
    firebase_messaging: ^14.3.0
    
dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:

    uses-material-design: true

    assets:
        - assets/images/
